### ISSUE TITLE
Running without GDAL（For example, Landsat TM images）

### ISSUE THREAD

**Issue by zhengzihao** [cordmaur/WaterDetect#10]
I have updated the process in "**Running without GDAL**" with reference to the media article ([Water Detection in High Resolution Satellite Images using the waterdetect python package](https://towardsdatascience.com/water-detection-in-high-resolution-satellite-images-using-the-waterdetect-python-package-7c5a031e3d16)) that describes it in more detail. 

Here, I use **waterdetect** to extract water bodies from a scene of **Landsat TM** imagery.
## Code part
 `import waterdetect as wd`
 `import rasterio`
 `from osgeo import gdal`

 `!waterdetect -GC`

> Copying c:\users\gw_studio\documents\miniconda3\lib\site-packages\WaterDetect.ini into current dir.
> WaterDetect.ini copied into C:\Users\GW_Studio\Documents\PythonCode.

 `config = wd.DWConfig(config_file='WaterDetect.ini')`

> Loading configuration file WaterDetect.ini
> File WaterDetect.ini verified.

 `config.clustering_bands, config.detect_water_cluster`

>  ([['mndwi', 'ndwi', 'Mir2']], 'maxmbwi')

`b2  = rasterio.open('D:\LT05\LT05_L1TP_122044_19911117_20200915_02_T1_B2.tif').read()`
`b3  = rasterio.open('D:\LT05\LT05_L1TP_122044_19911117_20200915_02_T1_B3.tif').read()`
`nir = rasterio.open('D:\LT05\LT05_L1TP_122044_19911117_20200915_02_T1_B4.tif').read()`
`mir1 = rasterio.open('D:\LT05\LT05_L1TP_122044_19911117_20200915_02_T1_B5.tif').read()`
`mir2 = rasterio.open('D:\LT05\LT05_L1TP_122044_19911117_20200915_02_T1_B7.tif').read()`
`b2.shape, b3.shape, nir.shape, mir1.shape, mir2.shape`

> ((1, 6694, 7198),
 (1, 6694, 7198),
 (1, 6694, 7198),
 (1, 6694, 7198),
 (1, 6694, 7198))

`bands = {'Green': b2.squeeze(), 'Red': b3.squeeze(), 'Nir': nir.squeeze(),'Mir': mir1.squeeze(),'Mir2': mir2.squeeze()}`
`wmask = wd.DWImageClustering(bands=bands, bands_keys=['Mir2', 'mndwi', 'ndwi'], invalid_mask=None, glint_processor=None, config=config)`
`mask = wmask.run_detect_water()`

> Selection of best number of clusters using Calinski-Harabasz Index:
> k=2 :Calinski_harabaz index=525017.1368054692
> k=3 :Calinski_harabaz index=272406.8028330963
> k=4 :Calinski_harabaz index=414875.9712176703
> k=5 :Calinski_harabaz index=600524.7602326183
> k=6 :Calinski_harabaz index=480991.67515900405
> k=7 :Calinski_harabaz index=508319.4897511767
> k=8 :Calinski_harabaz index=436496.13557214226
> k=9 :Calinski_harabaz index=423649.7968669792
> k=10 :Calinski_harabaz index=376965.3596922822
> Applying clusters based naive bayes classifier
> Assgnin 1 to cluster_id 3
> Skipping cluster_id 3

`import matplotlib.pyplot as plt`
`plt.imshow(wmask.cluster_matrix)`

> ![image](https://user-images.githubusercontent.com/8576149/120818694-6c1b9000-c585-11eb-85dd-cd01fdde5236.png)

`save_ay = wmask.cluster_matrix`
`dataset=gdal.Open("D:\LT05\LT05_L1TP_122044_19911117_20200915_02_T1_B2.tif")`
`im_geotrans = dataset.GetGeoTransform()`
`im_proj = dataset.GetProjection()`
`save = wd.DWutils.array2raster(filename='test.tif', array=save_ay, geo_transform=im_geotrans, projection=im_proj, nodatavalue=-1, dtype=None)`

> Saving image: test.tif

## Local results

- "test.tif" loaded in ArcGIS Pro

![image](https://user-images.githubusercontent.com/8576149/120819342-0f6ca500-c586-11eb-8f06-3234011ab7a8.png)

- Water pixel extracted from "test.tif"

![image](https://user-images.githubusercontent.com/8576149/120819528-404cda00-c586-11eb-8693-e1d96661ccc6.png)

- Compare with the raw satellite image

![image](https://user-images.githubusercontent.com/8576149/120819668-5e1a3f00-c586-11eb-9674-f19a9d37dc8c.png)

**Comment by cordmaur** [comment]
Hi @zhengzihao , 

So, what did you think about the overall results with Landsat images?

Thanks for sharing.
Mauricio

**Comment by zhengzihao** [comment]
> Hi @zhengzihao ,
> 
> So, what did you think about the overall results with Landsat images?
> 
> Thanks for sharing.
> Mauricio

Hi @cordmaur ,
I have just apply waterdetect on single TM image, and from the result so far, it's performing great! Especially, it can effectively separate the shadows of the tall buildings and water bodies.
Thank you for developing and opening source for wd.
Best wish！
Zihao

**Comment by cordmaur** [comment]
Thanks for sharing.
