### ISSUE TITLE
Multiple bands detected from S2B L1A S2COR

### ISSUE THREAD

**Issue by andreabenedetti** [cordmaur/WaterDetect#11]
Hi,

I'm having some issues in trying to run correctly waterdetect. I tried to use it on a variety of imagery from Copernicus but it failed everytime.

I'm trying to run it on this specific tile `S2B_MSIL2A_20210613T070619_N0300_R106_T40TEM_20210613T085847.SAFE`, which should be compatible with the product `S2_S2COR`. However, when waterdetect runs, it returns this error:

```
Loading configuration file WaterDetect.ini
File WaterDetect.ini verified.
Folder /Volumes/ANSSD/testFolder/input_folder verified.
Folder /Volumes/ANSSD/testFolder/output_folder verified.
Starting WaterDetection version: 1.5.8
Opening image in folder /Volumes/ANSSD/testFolder/input_folder/S2B_MSIL2A_20210613T070619_N0300_R106_T40TEM_20210613T085847.SAFE
Retrieving bands for product S2_S2COR
70 were found:
Loading band: Blue
****** WARNING ********
More than one band _B02_10m. in image list. Skipping to the next image
```

Do you have any insight on how to fix it and correctly run waterdetect?

Thanks in advance!

**Comment by cordmaur** [comment]
Hi, 
It is strange because it is finding exactly the the double of bands in your image. That's why it is raising an exception.
I have just tested here and take a look a the results. 

```
Loading configuration file WaterDetect.ini
File WaterDetect.ini verified.
Folder d:/images/input/Input_S2COR verified.
Folder d:/temp verified.
Starting WaterDetection version: 1.5.8
Opening image in folder d:\images\input\Input_S2COR\S2A_MSIL2A_20180819T105031_N0208_R051_T31TCM_20180819T145346.SAFE
Retrieving bands for product S2_S2COR
35 were found:
Loading band: Blue
Loading band: Green
Loading band: Red
Loading band: Mir
Loading band: Mir2
Loading band: RedEdg1
Loading band: RedEdg2
Loading band: RedEdg3
Loading band: Nir
Loading band: Nir2
```
Please, check inside your img_folder/GRANULE/L2A_T40TEM_xxxxxxx/IMG_DATA
You should have 3 folders:
```
R10m
R20m
R30m
```

Inside R10m you should have something like this...
![image](https://user-images.githubusercontent.com/19617404/121898740-fdc49380-cd23-11eb-9ee1-eaadde78695a.png)

Let me know if there are any inconsistencies. 

Mauricio

**Comment by andreabenedetti** [comment]
It's weird, I tried with another image but the results were the same: 70 bands found, exactly double what should be expected. The folders structure is the same, and the R10m contains something similar to the one you used:
<img width="323" alt="Screenshot 2021-06-14 at 15 39 36" src="https://user-images.githubusercontent.com/9431034/121901490-bc81b300-cd26-11eb-8e56-8708e31b205c.png">

**Comment by andreabenedetti** [comment]
A small update: it also happens with images using the product `S2_L1C`. Maybe it's a problem of the source of the images? This is the error message:
```
(base) andrea@Andreas-MacBook-Pro WaterDetect-1.5.8 % python runWaterDetect.py -i /Volumes/ANSSD/testFolder/input_folder -o /Volumes/ANSSD/testFolder/output_folder -p S2_L1C
Loading configuration file WaterDetect.ini
File WaterDetect.ini verified.
Folder /Volumes/ANSSD/testFolder/input_folder verified.
Folder /Volumes/ANSSD/testFolder/output_folder verified.
Starting WaterDetection version: 1.5.8
Opening image in folder /Volumes/ANSSD/testFolder/input_folder/S2A_MSIL1C_20210602T064631_N0300_R020_T40TGP_20210602T093931.SAFE
Retrieving bands for product S2_L1C
28 were found:
Loading band: Blue
****** WARNING ********
More than one band _B02. in image list. Skipping to the next image
```

**Comment by cordmaur** [comment]
I have only seen such problem when we open the bands in a different software that creates auxiliary files with the name similar to the names of the bands. 
Can you share this image so I can take a look at it?

**Comment by andreabenedetti** [comment]
First image, using product S2_S2COR: [https://scihub.copernicus.eu/dhus/odata/v1/Products('d841af68-b47e-4515-af3b-de234995c6b8')/$value](https://scihub.copernicus.eu/dhus/odata/v1/Products('d841af68-b47e-4515-af3b-de234995c6b8')/$value)
Second image, using product S2_L1C: [https://scihub.copernicus.eu/dhus/odata/v1/Products('4a8e5558-2c01-4fc8-a117-9a083ee0624b')/$value](https://scihub.copernicus.eu/dhus/odata/v1/Products('4a8e5558-2c01-4fc8-a117-9a083ee0624b')/$value)

**Comment by cordmaur** [comment]
Hi Andrea, I downloaded the images and ran the waterdetect. Here is the output:
![image](https://user-images.githubusercontent.com/19617404/122028493-610a0080-cdcc-11eb-9f31-717f602db7bb.png)

The image is normal and the code is working.
To check what is going on, I suggest you follow these commands on Jupyter:

![image](https://user-images.githubusercontent.com/19617404/122029650-5603a000-cdcd-11eb-990a-807b65772210.png)

This is the function I use to retrieve the bands in the product to filter them afterwards.
This way, we can see everything that the code is finding in your drive.
Let me know of the results.

PS: just for my statistics purposes, can you let me know where are you from? Country and University/Enterprise?

Regards,

**Comment by andreabenedetti** [comment]
It's still not working, but I think I'm understanding where the issue lies: the tiles I downloaded don't have a `R30m` folder, rather a `R60m` folder, which probably contains a different set of information than what waterdetect expects. 

However I'm struggling to understand which kind of imagery I am supposed to use with this script, since I downloaded tiles from the Sentinel 2 satellite, of the type S2A and L2A. 

Regarding my background: I'm a researcher and PhD candidate in design from Italy, specifically Politecnico di Milano at the Design Department!

**Comment by cordmaur** [comment]
Andrea,

I did a mistake on my previous posts. The folders inside IMG_DATA are:
```
R10m
R20m
R60m
```

I have ran my last test with the images downloaded from the link you provided, so they are exactly the same images. 
It may be something in the system or any previous processing you may have done. 
If could create a DWLoader as I showed, it will be easier to debug the problem.

Regards,
Mauricio

**Comment by andreabenedetti** [comment]
Hi Mauricio,

problem is, the DWLoader doesn't recognize the images as valid S2COR imagery! I didn't manipulate them in any way, I just downloaded them straight from Copernicus. Here is the Jupyter notebook:

<img width="865" alt="Screenshot 2021-06-17 at 14 56 49" src="https://user-images.githubusercontent.com/9431034/122400710-41b1d580-cf7c-11eb-9c5a-18fc9ed40a8c.png">

And here the image folder:
<img width="386" alt="Screenshot 2021-06-17 at 14 58 07" src="https://user-images.githubusercontent.com/9431034/122400942-76259180-cf7c-11eb-972a-9420ed9af00e.png">

Thank you for your patience! I'm fairly new to this kind of image processing and analysis :)

**Comment by cordmaur** [comment]
Hi Andrea,
No problem. We need to find out what's going on. But it's weird as the first problem is that it was finding the double of bands, and now it finds none. 
I will ask you to follow these commands to try to debug the issue (if you are running linux, you change dir for ls):

![image](https://user-images.githubusercontent.com/19617404/122520708-3f9b5580-d014-11eb-91d0-233aad9252db.png)

And then, we will take a look inside the image.
![image](https://user-images.githubusercontent.com/19617404/122520395-d61b4700-d013-11eb-8f00-81dca5fe642a.png)

Finally we will check if the configuration is good for opening it. If everything matches, it should work at this point.
![image](https://user-images.githubusercontent.com/19617404/122520661-2f837600-d014-11eb-8828-82e2074dc2fa.png)

**Comment by andreabenedetti** [comment]
Hi Mauricio,

thanks! I'm running the code. Everything is the same up to the last step. Here the breakdown.

**Loading folder**
<img width="1017" alt="Screenshot 2021-06-18 at 10 14 09" src="https://user-images.githubusercontent.com/9431034/122529696-0c5dc400-d01e-11eb-9a97-ce3cf470a129.png">
**Looking at the images**
<img width="1495" alt="Screenshot 2021-06-18 at 10 14 23" src="https://user-images.githubusercontent.com/9431034/122529707-0e278780-d01e-11eb-9242-903b98a22d30.png">
**Configuration check**
<img width="1220" alt="Screenshot 2021-06-18 at 10 14 30" src="https://user-images.githubusercontent.com/9431034/122529711-0f58b480-d01e-11eb-9cc6-39ae55619b03.png">

**Comment by andreabenedetti** [comment]
Just for reference, the image I'm trying to analyze is this one, so I think there should definitely be some water detected! :) 
![Screenshot 2021-06-18 at 10 19 22](https://user-images.githubusercontent.com/9431034/122530581-e97fdf80-d01e-11eb-8449-d3924e0dfc23.png)

**Comment by cordmaur** [comment]
It's strange because the first error you've sent me was because it was finding the double of bands, and now it finds no bands. 
And this image is different from the one you asked me to download, but that's not the issue. 

We have to debug it. I don't know if you are familiar with, but let's the basics. 

Try to run `loader.get_bands_files()` and wait for the error.
In the next cell you type:
`%debug `and shift+enter

inside the debuger you will type the following commands (one at a time) and check the results: 

`> self.bands_path `

`> self.product_dict`

`> [f for f in self.bands_path.rglob('*.jp2')]`

Here is an example (note that I changed the product to S2_THEIA to force an error at the same point)
![image](https://user-images.githubusercontent.com/19617404/122588085-f3c1ce00-d05e-11eb-8018-b634b2928433.png)

If it does not return anything, try the `rglob('*')` to "see" what the class is seeing. 

This is the image you sent me the link, already processed.
![image](https://user-images.githubusercontent.com/19617404/122590116-6469ea00-d061-11eb-826a-7d47289ed0ba.png)

Just be aware that it has a lot of sun glint (you can check it on the PDF report also) and you may have to adjust the configuration depending on the objectives (include x exclude the glint, for example). 
![image](https://user-images.githubusercontent.com/19617404/122590232-8bc0b700-d061-11eb-80b9-3793e540b2bd.png)

**Comment by andreabenedetti** [comment]
Hi Mauricio,

thanks for the patience! I ran the code you wrote, however when running `[f for f in self.bands_path.rglob('*.jp2')]` the result is an empty array, even when running `[f for f in self.bands_path.rglob('*')]`.

Here the logs:
<img width="857" alt="Screenshot 2021-06-21 at 09 45 41" src="https://user-images.githubusercontent.com/9431034/122725777-a0759880-d275-11eb-8a04-0604687199e8.png">

**Comment by cordmaur** [comment]
Andrea. You have to run the tests mentioned here (https://github.com/cordmaur/WaterDetect/issues/11#issuecomment-863852114) again. And then do the debug when the error occurs. Note that the Path shown in the debug is “duplicated” and it does not match the path shown in the previous post.

**Comment by cordmaur** [comment]
Hi @andreabenedetti , could you succeed to solve the problem?

**Comment by haozhen315** [comment]
I have downloaded the imgaes with the links provided in this post and just fresh downloaded waterdetect
with running:
python runWaterDetect.py -i /Volumes/SanDisk/DownloadSanDisk/Test_S2COR -o /Volumes/SanDisk/DownloadSanDisk/Test_S2COR_Out -p S2_S2COR

and I have got the result, so I believe there is no problem with author's code. test on Mac

**Comment by cordmaur** [comment]
Thanks @haozhen315
