### ISSUE TITLE
Problems with S2_L1C Images

### ISSUE THREAD

**Issue by fede1608** [cordmaur/WaterDetect#12]
Hi! 
I'm experiencing  some troubles trying to run the script with a S2_L1C image, particularly this one: [https://scihub.copernicus.eu/dhus/odata/v1/Products('ea4dfeee-1d28-47c5-a6a8-c86ada64768f')/$value](https://scihub.copernicus.eu/dhus/odata/v1/Products('ea4dfeee-1d28-47c5-a6a8-c86ada64768f')/$value)

It seems to be some sorts of recursive problem, not sure exactly what.

This is the console output:

> (base) Macbook-Pro-2020-de-*******:WaterDetect ******$ python runWaterDetect.py  -i ./Input/ -o ./Output/ -s ../../../Downloads/LaJara/LaJara.shp --product S2_L1C
Loading configuration file WaterDetect.ini
File WaterDetect.ini verified.
Folder ./Input/ verified.
File ../../../Downloads/LaJara/LaJara.shp verified.
Folder ./Output/ verified.
Starting WaterDetection version: 1.5.10
Opening image in folder Input/S2A_MSIL1C_20210207T174511_N0209_R098_T13SDA_20210207T212818.SAFE
Retrieving bands for product S2_L1C
****** WARNING ********
[Errno 2] No such file or directory: 'Input/S2A_MSIL1C_20210207T174511_N0209_R098_T13SDA_20210207T212818.SAFE/GRANULE/Input/S2A_MSIL1C_20210207T174511_N0209_R098_T13SDA_20210207T212818.SAFE/GRANULE/L1C_T13SDA_A029410_20210207T175338/IMG_DATA'. Skipping to the next image

I was not able to find any other image source for that particular place.
I'm on MacOS Big Sur, and the latest version of the script.

**Comment by cordmaur** [comment]
Hi @fede1608 ,

I did a minor correction on the InputOutput.py, based on the comments of another user that had a similar issue as you had. As I am using windows and this problem don't occur to me, I cannot test it correctly at the moment. 

If you can clone the project and test it again... I will upload a new version to PyPI if it works. 

For your image, here is an example of the output. Be aware that, as you are working with L1C images, there is no layer with pre-defined masks, so you need to take care of the snow pixels beforehand (passing an external mask) or change the .ini to try to clip these values according to the reflectance on the visible. 
![image](https://user-images.githubusercontent.com/19617404/141085741-6cb79c12-a609-4482-b130-caed4debf34d.png)

Regards,
Mauricio

**Comment by fede1608** [comment]
Thanks! It worked fine!
