### ISSUE TITLE
skip re-processing of existing results

### ISSUE THREAD

**Issue by johntruckenbrodt** [cordmaur/WaterDetect#13]
Hi there. Nice package! I am currently giving it a try processing some S2_THEIA products. I have unpacked several products to a directory and run the package with
```
waterdetect -i ./in -o ./out -p S2_THEIA
```
I wanted to unpack some more scenes into my source directory and run the program again but it basically ignores the existing output and starts processing them again.  
It would be fantastic if repeated runs would leave existing products untouched.

Cheers,
John

P.S. I think there is a small typo in the README:
```diff
- waterdetect -i c:/input_folder -i -c:/output_folder -p S2_THEIA
+ waterdetect -i c:/input_folder -o -c:/output_folder -p S2_THEIA
```

**Comment by cordmaur** [comment]
Thanks for the typo. The skipping feature is not in the roadmap at the moment, but thanks for the suggestion.
