### ISSUE TITLE
'DWWaterDetect' has no attribute 'run_single'

### ISSUE THREAD

**Issue by cmorenoUCB2021** [cordmaur/WaterDetect#15]
Hi, 
Thank you for creating this library.  It looks great. I am trying to use it to detect water in some satellite images.  We have the 'tif' files (i.e. S2B_MSIL2A_20220508T155819_N0400_R097_T17RLN_20220508T205707_1018.tif).  The tif file is already sized to a 3.5 miles by 3.5 mile.  However, we get the following error -> 'DWWaterDetect' has no attribute 'run_single'.

In addition, I am not sure the reason for using the shape file 

This is how we are calling the function - do we need a shape file or is it optional?  Thank you in advance for your help.

water_mask = wd.DWWaterDetect.run_single(image_folder='Img/',
                                         temp_folder='tmp/'
                                       #  shape_file='D:/Shp/Area_Tiete.shp'
                                        )

**Comment by cordmaur** [comment]
Can you provide the code snippet you are using? 
This command ` wd.DWWaterDetect.run_single` doesn't seem right.

**Comment by cordmaur** [comment]
Closed due to inactivity.
