### ISSUE TITLE
Clipping input data to the valid range kill the process

### ISSUE THREAD

**Issue by Digdgeo** [cordmaur/WaterDetect#16]
Hi, 

First of all, thank you so much for the package. I am trying to run it from both (notebook and Terminal window) but I always get this error message: 

"Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers)"

The whole output is this one:

 Opening image in folder /home/diego/EBD/Varios/Sentinel2_Flood/imgs/sen2cor/S2B_MSIL2A_20220501T110619_N0400_R137_T30STG_20220501T131135.SAFE
Retrieving bands for product S2_S2COR
36 were found:
Loading band: Blue
Loading band: Green
Loading band: Red
Loading band: Mir
Loading band: Mir2
Loading band: RedEdg1
Loading band: RedEdg2
Loading band: RedEdg3
Loading band: Nir
Loading band: Nir2
Warning: External mask None not found!
Invalid pixels (0.23079226678080034) < maximum (0.95).
Saving final MASK
Saving image: /home/diego/EBD/Varios/Sentinel2_Flood/outputs/S2B_MSIL2A_20220501T110619_N0400_R137_T30STG_20220501T131135/S2B_MSIL2A_20220501T110619_N0400_R137_T30STG_20220501T131135_invalid_mask.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
Input file size is 10980, 10980
0...10...20...30...40...50...60...70...80...90...100 - done.
Calculating clusters for the following combination of bands:
['mndwi', 'ndwi', 'Mir2']
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Terminado (killed)

I'd appreciate your help.

**Comment by cordmaur** [comment]
You should check your memory consumption. It usually needs 32Gb to run an entire tile. Otherwise you can pass a shape to clip to an area of interest.
