### ISSUE TITLE
 error during clustering -No such file or directory of 'img_composite.pdf' in the output directory

### ISSUE THREAD

**Issue by HEGIT2018** [cordmaur/WaterDetect#18]
Hi,

 thank you so much for the package and I was testing the sentinel-2 with single mode. Weather the pdf_reports = True or False and the create_composite =True or Flase, the error 'No such file or directory : 'Output/data/data_composite.pdf' happened. Would you please give me any advice?

cheers.

**Comment by cordmaur** [comment]
Hi @HEGIT2018,  are you still facing issues with the package? Sorry for the delay.
