### ISSUE TITLE
****** WARNING ******** 'recursive'. Skipping to the next image

### ISSUE THREAD

**Issue by Hello-JoshuaLee** [cordmaur/WaterDetect#23]
Hello, thank you for your outstanding work.
 When I successfully installed the waterdetcet package on windows and used it to process landsat8 data, But the error is displayed `****** WARNING ********'recursive'. Skipping to the next image`.
 I don't know how to solve it. I hope you can help me.
![image](https://user-images.githubusercontent.com/125441435/222423214-217d8dea-b728-450a-9f8b-f69134322f64.png)

**Comment by cordmaur** [comment]
Hi @Hello-JoshuaLee , can you provide a direct link to the image you are using so we can check?
