### ISSUE TITLE
How to actually run the script

### ISSUE THREAD

**Issue by souvik0306** [cordmaur/WaterDetect#25]
This may seem very broad, but How to run the script?

What type of images does the script support? JPG, PNG, JPEG, or something else?

If so, then where can I get those images?

After that how to run the code step by step?

**Comment by souvik0306** [comment]
Also what is shape file? 

```
wd.DWWaterDetect.run_batch(input_folder=input_folder,
                           output_folder=output_folder                          )
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[16], line 1
----> 1 wd.DWWaterDetect.run_batch(input_folder=input_folder,
      2                            output_folder=output_folder                          )

AttributeError: type object 'DWWaterDetect' has no attribute 'run_batch'

**Comment by crackwitz** [comment]
also asked here: https://stackoverflow.com/questions/76080276/how-to-execute-the-water-detect-python-package-for-remote-sensing

**Comment by souvik0306** [comment]
yeah thats me

**Comment by NourSoltani** [comment]
Greetings!
Try to replace it with the following:
water_mask = wd.DWWaterDetect.run_water_detect(input_folder='Input/Path',output_folder='Output/path',shape_file= None,product=wd.DWProducts.Sentinel2_THEIA,config_file='/mnt/WaterDetect.ini',single_mode=False)
If you have multiple Image, keep single_mode=False, and the Input Folder should be the parent directory.
If you want to work on only One Image, then single_mode=True, and the input_folder should be the path of image's folder. 
Hope this answers your question.

**Comment by cordmaur** [comment]
@NourSoltani , thanks for the answer. I corrected the `read.me` according to the newest version.
 
@souvik0306 , this package is intended for use with satellite images only. Actually it supports Sentinel2 (ESA's SAFE and THEIA's formats) and Landsat8 (USGS format). Shapefile is an usual format for describing vectorial data. It can be used to restrict the output to an area of interest (e.g., a basin or a city). 
I suggest you to take a look at Landsat and Sentinel2 products to check if they fit your needs.
