### ISSUE TITLE
Not able to reproduce result

### ISSUE THREAD

**Issue by VaasuDevanS** [cordmaur/WaterDetect#29]
Hello @cordmaur, Thanks very much for open sourcing this work.

I was following the code from this blog (https://www.geocorner.net/post/water-detection-in-high-resolution-satellite-images-using-the-waterdetect-python-package) especially `Running without GDAL` section for my own Sentinel-2 L2A image.

I modified the .ini file to produce this output
<img width="575" alt="image" src="https://github.com/user-attachments/assets/e4aab12c-9a9a-43c3-8e24-308c242e97b0">

But when generating the result, `OSError: Required bands not informed: {'Mir2'}` error occurs. I tried debugging the source code but couldn't find why Mir2 is required.

1. Is Mir2 mandatory for generating the result? (Because Mir2 is in Landsat and I want to generate result using Sentinel-2)
2. What's the use of bands_keys in the following line of code
```python
wmask = wd.DWImageClustering(bands=bands, bands_keys=['Nir', 'ndwi'], invalid_mask=None, config=config)
```

Associated files for reproducing the issue:
- [WaterDetect.ini.zip](https://github.com/user-attachments/files/16336885/WaterDetect.ini.zip)
- Colab Notebook: https://colab.research.google.com/drive/1Aqhy_nL9gc7qoVqZ15S9XQBtIeCoLwCr

**Comment by cordmaur** [comment]
Hi @VaasuDevanS ,
In WaterDetect, Mir2 = B12 (Sentinel2). 
Although you are not using it for the clustering process, it is still being used in your `.ini` file, to clip outliers (look below). 

![image](https://github.com/user-attachments/assets/883dca07-e846-40e3-bf33-1b57bbdfcc06)

You can change the band to `NIR` or just set `None` to all thresholds. 

Hope that helps.

**Comment by VaasuDevanS** [comment]
> just set `None` to all thresholds

Setting this to `None` helped. Thanks very much for your comment.
