### ISSUE TITLE
Support required

### ISSUE THREAD

**Issue by Krish-newbie** [cordmaur/WaterDetect#8]
Hello,

I am newbie and trying to replicate this project on a EC2 instance and i have completed all the setup, created input and output folders in in the instance.

I would like to know what file format i should upload in to the input folder to run the water detect command? can i use the sentinel open data on aws? if yes, can you direct me to the right file type.

Thank you for your support

**Comment by cordmaur** [comment]
Hi Krish,

I am not an AWS user. But the input folder should contain L2A (ESA/SEN2COR
or THEIA/MAJA) unzipped files. Like so:
Just make sure to set correctly the -p (Product Type) flag, with the type
of product you are feeding it.

[image: image.png]

Regards,
Mauricio


Em qua., 24 de mar. de 2021 às 09:01, Krish-newbie ***@***.***>
escreveu:

**Comment by Krish-newbie** [comment]
Hi Mauricio,

Thank you for your quick response. When i access the sentinel 2 archive open data repository (https://registry.opendata.aws/sentinel-2/) i see folders on date basis. Inside the date folder, i see two files one is a json file and one is a checksum file. Is that what i need to upload or i am looking at the wrong thing?
Also i have GDAL installation issue. Tried many times but unable to have the GDAL for some weird reason. I will try again.
I am doing this on Amazon Linux version.
Thank you for your guidance.

**Comment by Krish-newbie** [comment]
<img width="869" alt="Screenshot 2021-03-31 at 2 09 49 PM" src="https://user-images.githubusercontent.com/63696611/113098270-db45d280-922a-11eb-8319-a2cff87fc5bd.png">

Hi, i have installed GDAL, but the WaterDetect i still saying GDAL is not installed. I have attached the screenshot from the console. Can you take a look at it and let me know what could be the issue?

**Comment by cordmaur** [comment]
Hi Krish,
If you look at the __ini__.py you will notice that I have a try...except block to check if gdal imports correctly:

```
try:
    from osgeo import gdal
    # just imports DWWaterDetect if gdal is present
    from waterdetect.WaterDetect import DWWaterDetect

except BaseException as error:
    # print(error)
    print('GDAL not found in environment. Waterdetect can still run as API calling DWImageClustering and passing'
          ' the arrays as dictionary. Refer to online documentation. No call to DWWaterDetect, that requires '
          'loading satellite images from disk will be possible')
    gdal = None
```
Check here in PyPI docs (https://pypi.org/project/GDAL/)  that from `osgeo import gdal` is the current usage and `import gdal` is (or will be) deprecated.

To see if you have it correctly installed, I suggest you open ipython in this environment and type from osgeo import gdal and check if it imports correctly. Please, let me know if you suceed.

**Comment by mazingaro** [comment]
@cordmaur 
I have the same issue: GDAL is installed and it is importing with `from osgeo import gdal` in python.
I tried it within a python 3.5 environment.

**Comment by cordmaur** [comment]
@mazingaro Can you copy here the error?
You can also install GDAL from conda-forge channel using conda.

**Comment by mazingaro** [comment]
I've removed Python 3.5, so this is the output from 3.8. There are two errors: one i the import of GDAL and the other the import of the import of calinski_harabaz_score, which [seems to have changed it's name](https://stackoverflow.com/questions/63482327/importerror-cannot-import-name-calinski-harabaz-score-from-sklearn-metrics).
```

GDAL not found in environment. Waterdetect can still run as API calling DWImageClustering and passing the arrays as dictionary. Refer to online documentation. No call to DWWaterDetect, that requires loading satellite images from disk will be possible

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-ddf707805fde> in <module>
      1 get_ipython().run_line_magic('load_ext', 'autoreload')
      2 get_ipython().run_line_magic('autoreload', '2')
----> 3 import waterdetect as wd

~/Documents/obmocja_razlivanja/WaterDetect/waterdetect/__init__.py in <module>
     22     gdal = None
     23 
---> 24 from waterdetect.Image import DWImageClustering
     25 from waterdetect.Common import DWutils, DWConfig
     26 

~/Documents/obmocja_razlivanja/WaterDetect/waterdetect/Image.py in <module>
      2 from sklearn import cluster
      3 from sklearn import metrics
----> 4 from sklearn.metrics import calinski_harabaz_score
      5 from sklearn.naive_bayes import GaussianNB
      6 from sklearn.neural_network import MLPClassifier

ImportError: cannot import name 'calinski_harabaz_score' from 'sklearn.metrics' (/home/mazinga/.local/lib/python3.8/site-packages/sklearn/metrics/__init__.py)

```

**Comment by cordmaur** [comment]
There is a new release to fix the GDAL issue. Closing this thread.
